// Generated by gencpp from file gps/InitializePose.msg
// DO NOT EDIT!


#ifndef GPS_MESSAGE_INITIALIZEPOSE_H
#define GPS_MESSAGE_INITIALIZEPOSE_H

#include <ros/service_traits.h>


#include <gps/InitializePoseRequest.h>
#include <gps/InitializePoseResponse.h>


namespace gps
{

struct InitializePose
{

typedef InitializePoseRequest Request;
typedef InitializePoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitializePose
} // namespace gps


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gps::InitializePose > {
  static const char* value()
  {
    return "73febd61b8e953d7433f73e2e36e8177";
  }

  static const char* value(const ::gps::InitializePose&) { return value(); }
};

template<>
struct DataType< ::gps::InitializePose > {
  static const char* value()
  {
    return "gps/InitializePose";
  }

  static const char* value(const ::gps::InitializePose&) { return value(); }
};


// service_traits::MD5Sum< ::gps::InitializePoseRequest> should match
// service_traits::MD5Sum< ::gps::InitializePose >
template<>
struct MD5Sum< ::gps::InitializePoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gps::InitializePose >::value();
  }
  static const char* value(const ::gps::InitializePoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gps::InitializePoseRequest> should match
// service_traits::DataType< ::gps::InitializePose >
template<>
struct DataType< ::gps::InitializePoseRequest>
{
  static const char* value()
  {
    return DataType< ::gps::InitializePose >::value();
  }
  static const char* value(const ::gps::InitializePoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gps::InitializePoseResponse> should match
// service_traits::MD5Sum< ::gps::InitializePose >
template<>
struct MD5Sum< ::gps::InitializePoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gps::InitializePose >::value();
  }
  static const char* value(const ::gps::InitializePoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gps::InitializePoseResponse> should match
// service_traits::DataType< ::gps::InitializePose >
template<>
struct DataType< ::gps::InitializePoseResponse>
{
  static const char* value()
  {
    return DataType< ::gps::InitializePose >::value();
  }
  static const char* value(const ::gps::InitializePoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GPS_MESSAGE_INITIALIZEPOSE_H
