// Generated by gencpp from file gps/InitializePoseRequest.msg
// DO NOT EDIT!


#ifndef GPS_MESSAGE_INITIALIZEPOSEREQUEST_H
#define GPS_MESSAGE_INITIALIZEPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gps
{
template <class ContainerAllocator>
struct InitializePoseRequest_
{
  typedef InitializePoseRequest_<ContainerAllocator> Type;

  InitializePoseRequest_()
    : request(false)  {
    }
  InitializePoseRequest_(const ContainerAllocator& _alloc)
    : request(false)  {
  (void)_alloc;
    }



   typedef uint8_t _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::gps::InitializePoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gps::InitializePoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InitializePoseRequest_

typedef ::gps::InitializePoseRequest_<std::allocator<void> > InitializePoseRequest;

typedef boost::shared_ptr< ::gps::InitializePoseRequest > InitializePoseRequestPtr;
typedef boost::shared_ptr< ::gps::InitializePoseRequest const> InitializePoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gps::InitializePoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gps::InitializePoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gps::InitializePoseRequest_<ContainerAllocator1> & lhs, const ::gps::InitializePoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gps::InitializePoseRequest_<ContainerAllocator1> & lhs, const ::gps::InitializePoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gps

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gps::InitializePoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gps::InitializePoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gps::InitializePoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gps::InitializePoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps::InitializePoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps::InitializePoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gps::InitializePoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f7e5ad6ab0ddf42c5727a195315a470";
  }

  static const char* value(const ::gps::InitializePoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f7e5ad6ab0ddf42ULL;
  static const uint64_t static_value2 = 0xc5727a195315a470ULL;
};

template<class ContainerAllocator>
struct DataType< ::gps::InitializePoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gps/InitializePoseRequest";
  }

  static const char* value(const ::gps::InitializePoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gps::InitializePoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool request\n"
;
  }

  static const char* value(const ::gps::InitializePoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gps::InitializePoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitializePoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gps::InitializePoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gps::InitializePoseRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "request: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPS_MESSAGE_INITIALIZEPOSEREQUEST_H
