// Generated by gencpp from file gps/InitializePoseResponse.msg
// DO NOT EDIT!


#ifndef GPS_MESSAGE_INITIALIZEPOSERESPONSE_H
#define GPS_MESSAGE_INITIALIZEPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gps
{
template <class ContainerAllocator>
struct InitializePoseResponse_
{
  typedef InitializePoseResponse_<ContainerAllocator> Type;

  InitializePoseResponse_()
    : success(false)  {
    }
  InitializePoseResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::gps::InitializePoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gps::InitializePoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InitializePoseResponse_

typedef ::gps::InitializePoseResponse_<std::allocator<void> > InitializePoseResponse;

typedef boost::shared_ptr< ::gps::InitializePoseResponse > InitializePoseResponsePtr;
typedef boost::shared_ptr< ::gps::InitializePoseResponse const> InitializePoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gps::InitializePoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gps::InitializePoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gps::InitializePoseResponse_<ContainerAllocator1> & lhs, const ::gps::InitializePoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gps::InitializePoseResponse_<ContainerAllocator1> & lhs, const ::gps::InitializePoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gps

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gps::InitializePoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gps::InitializePoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gps::InitializePoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gps::InitializePoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps::InitializePoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps::InitializePoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gps::InitializePoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::gps::InitializePoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::gps::InitializePoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gps/InitializePoseResponse";
  }

  static const char* value(const ::gps::InitializePoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gps::InitializePoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::gps::InitializePoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gps::InitializePoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitializePoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gps::InitializePoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gps::InitializePoseResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPS_MESSAGE_INITIALIZEPOSERESPONSE_H
