// Generated by gencpp from file planning/PathReferenceElement.msg
// DO NOT EDIT!


#ifndef PLANNING_MESSAGE_PATHREFERENCEELEMENT_H
#define PLANNING_MESSAGE_PATHREFERENCEELEMENT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace planning
{
template <class ContainerAllocator>
struct PathReferenceElement_
{
  typedef PathReferenceElement_<ContainerAllocator> Type;

  PathReferenceElement_()
    : pose()
    , mode(0)  {
    }
  PathReferenceElement_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , mode(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::planning::PathReferenceElement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planning::PathReferenceElement_<ContainerAllocator> const> ConstPtr;

}; // struct PathReferenceElement_

typedef ::planning::PathReferenceElement_<std::allocator<void> > PathReferenceElement;

typedef boost::shared_ptr< ::planning::PathReferenceElement > PathReferenceElementPtr;
typedef boost::shared_ptr< ::planning::PathReferenceElement const> PathReferenceElementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planning::PathReferenceElement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planning::PathReferenceElement_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planning::PathReferenceElement_<ContainerAllocator1> & lhs, const ::planning::PathReferenceElement_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planning::PathReferenceElement_<ContainerAllocator1> & lhs, const ::planning::PathReferenceElement_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::planning::PathReferenceElement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planning::PathReferenceElement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planning::PathReferenceElement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planning::PathReferenceElement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning::PathReferenceElement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning::PathReferenceElement_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planning::PathReferenceElement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03dbb4113f1f5815afcc98e104844d0b";
  }

  static const char* value(const ::planning::PathReferenceElement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03dbb4113f1f5815ULL;
  static const uint64_t static_value2 = 0xafcc98e104844d0bULL;
};

template<class ContainerAllocator>
struct DataType< ::planning::PathReferenceElement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planning/PathReferenceElement";
  }

  static const char* value(const ::planning::PathReferenceElement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planning::PathReferenceElement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n"
"uint8 mode\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::planning::PathReferenceElement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planning::PathReferenceElement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathReferenceElement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planning::PathReferenceElement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planning::PathReferenceElement_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNING_MESSAGE_PATHREFERENCEELEMENT_H
